version: '3'

tasks:
  demo:
    vars:
      COMMAND: airflow-diagrams generate --airflow-dag-id dbt -o examples/
    cmds:
      # 1. Record demo as json
      - asciinema rec assets/json/demo_output.json -c "{{ .COMMAND }}" --overwrite
      # 2. Combine previous demo output and command
      - echo "{{ .COMMAND }}" | python3 dev/demo/demo_editor.py
      # 3. Convert demo to svg
      - docker run --rm -i -v $PWD/assets:/data bric3/svg-term-cli svg-term --in /data/json/demo_full.json --out /data/images/demo.svg --window --width 100
      # 4. Render diagram
      - cd examples && python3 dbt_diagrams.py
  airflow-download:
    cmds:
      # Pull latest data from airflow repo if exists else clone airflow repo
      - cd generated/airflow && git fetch && git pull || gh repo clone apache/airflow generated/airflow
  fake-dag:
    cmds:
      # 1. Create fake dag
      - python3 dev/airflow/airflow_dags_creator.py
      # 2. Generate diagram from fake dag
      - airflow-diagrams generate -f generated/airflow_dags_random.yml -o generated/ --export-matches generated/matches.yml -v
      # 3. Render diagram
      - cd generated && python3 random_dag_diagrams.py
  usage:
    cmds:
      # Convert --help output to carbon-now usage screenshot
      - airflow-diagrams generate --help | python3 dev/usage/usage_generator.py
